<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>8.0</LangVersion>
		<RootNamespace>UIChanges</RootNamespace>
		<Nullable>enable</Nullable>
		<WrathInstallDir>E:\SteamLibrary\steamapps\common\Pathfinder Second Adventure</WrathInstallDir>
		<BaseOutputPath>E:\Projects\SpontaneousGyronna\SpontaneousGyronna\bin</BaseOutputPath>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="AssemblyPublicizer" Version="1.0.2">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>
	<ItemGroup>
		<Reference Include="0Harmony">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\UnityModManager\0Harmony.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp">
		  <HintPath>lib\Assembly-CSharp_public.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="Owlcat.Runtime.Core">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\Owlcat.Runtime.Core.dll</HintPath>
		</Reference>
		<Reference Include="Owlcat.Runtime.UI">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\Owlcat.Runtime.UI.dll</HintPath>
		</Reference>
		<Reference Include="Owlcat.SharedTypes">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\Owlcat.SharedTypes.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityModManager">
			<HintPath>..\..\..\..\SteamLibrary\steamapps\common\Pathfinder Second Adventure\Wrath_Data\Managed\UnityModManager\UnityModManager.dll</HintPath>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<None Update="info.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	<Target Name="CopyDLLs" AfterTargets="Build">
		<Message Text="copying to Wrath folder" Importance="High" />
		<Copy SourceFiles="$(TargetDir)$(ProjectName).dll;$(TargetDir)info.json" DestinationFolder="$(WrathInstallDir)\Mods\$(ProjectName)" />
	</Target>
	<Target Name="Publicize" AfterTargets="Clean">
		<ItemGroup>
			<Assemblies Include="$(WrathInstallDir)\Wrath_Data\Managed\Assembly-CSharp.dll" />
		</ItemGroup>

		<PublicizeTask InputAssemblies="@(Assemblies)" OutputDir="$(SolutionDir)lib/" />
	</Target>
</Project>
